variables:
 rgName: 'Avengers-Infinity-War-dev-rg'
 location: 'uksouth'
 storageAccountName: 'avengersinfinitywardev'
 storageAccountContainers: 'tonystark,steverogers,thor,brucebanner,natasharomanoff,peterparker,drstrange,tchalla,gamora,nebula,loki' # IMPORTANT - MUST BE 'containername1,containername2' for containers to be created
 rgVirtualNetworksSubnets: 'beardynetwork-dev-rg/beardvnet-dev/Public,beardynetwork-dev-rg/beardvnet-dev/onprem,beardynetwork-dev-rg/beardvnet-dev/internal' # IMPORTANT - MUST BE 'RGName/vNetName/subnetName,RGName/vNetName/subnetName' The vNet/Subnet that will have the Private Endpoints
 peRGVnetSubnet: 'beardynetwork-dev-rg/beardvnet-dev/internal' # IMPORTANT - MUST BE 'RGName/vNetName/subnetName'
