variables:
 rgName: 'Captain-America-The-First-Avenger-prod-rg'
 location: 'uksouth'
 storageAccountName: 'captainamericathefiprod'
 storageAccountContainers: 'steverogers,nickfury,peggycarter,bucky' # IMPORTANT - MUST BE 'containername1,containername2' for containers to be created
 rgVirtualNetworksSubnets: 'beardynetwork-rg/beardvnet/Public,beardynetwork-rg/beardvnet/onprem,beardynetwork-rg/beardvnet/iamgroot' # IMPORTANT - MUST BE 'RGName/vNetName/subnetName,RGName/vNetName/subnetName' The vNet/Subnet that will have the Private Endpoints
 peRGVnetSubnet: 'beardynetwork-rg/beardvnet/iamgroot' # IMPORTANT - MUST BE 'RGName/vNetName/subnetName'
