# This is the default template for deploying many resource groups

# each one will contain 2 storage accounts and a number of containers and a private endpoint connected to the Admin Network

trigger: none # will disable CI builds (but not PR builds)


parameters:
- name: environments
  type: object
  default: ['dev'] #,'uat', 'prod']
- name: films
  type: object
  default: ['Ant-Man-and-the-Wasp'] 
  # ['Iron-Man','The-Incredible-Hulk','Iron-Man-2','Thor','Captain-America-The-First-Avenger','Marvels-The-Avengers','Iron-Man-3','Thor-The-Dark-World','Captain-America-The-Winter-Soldier','Guardians-of-the-Galaxy',	'Avengers-Age-of-Ultron','Ant-Man',	'Captain-America-Civil-War','Doctor-Strange',	'Guardians-of-the-Galaxy','Spider-Man-Homecoming','Thor-Ragnarok',	'Black-Panther',	'Avengers-Infinity-War','Ant-Man-and-the-Wasp','Captain-Marvel',	'Avengers-Endgame','Spider-Man-Far-From-Home','Black-Widow',	'Shang-Chi-and-the-Legend-of-the-Ten','Eternals',	'Spider-Man-No-Way-Home','Doctor-Strange-in-the-Multiverse-of-Madness','Thor-Love-and-Thunder',	'Black-Panther-Wakanda-Forever','The-Marvels','Guardians-of-the-Galaxy-Vol-3','Ant-Man-and-the-Wasp-Quantumania','Fantastic-Four']

stages:
- ${{ each film in parameters.films }}:
  - ${{ each env in parameters.environments }}:
    - stage: deploy_${{ film }}_${{ env }}_ResourceGroup
      dependsOn: [] 
      variables:          
        - template: variables/${{ film }}-${{ env }}.yaml
      jobs:
        - template: Bicep\myCustomResources\MultipleResourceGroups.bicep
          parameters:
            rgName: ${{ variables.rgName }}
            storageAccountName: ${{ variables.storageAccountName }}
            storageAccountContainers: ${{ variables.storageAccountContainers }}
            rgVirtualNetworksSubnets: ${{ variables.rgVirtualNetworksSubnets }}

